### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by zettam** [xseignard/thermalPrinter#16]
````
pi@pi ~/core/printer $ npm install thermalprinter --save
npm WARN package.json printer@1.0.0 No description
npm WARN package.json printer@1.0.0 No repository field.
npm WARN package.json printer@1.0.0 No README data
 
> sleep@1.2.0 install /home/pi/core/printer/node_modules/thermalprinter/node_modules/sleep
> node build.js || nodejs build.js

child_process: customFds option is deprecated, use stdio instead.
gyp: thermalprinter not found (cwd: /home/pi/core/printer/node_modules/thermalprinter/node_modules/sleep) while trying to load thermalprinter
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.10-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "thermalprinter" "--save"
gyp ERR! cwd /home/pi/core/printer/node_modules/thermalprinter/node_modules/sleep
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
[sleep]: Error: Failed to execute 'node-gyp rebuild thermalprinter --save' (1)
gyp: thermalprinter not found (cwd: /home/pi/core/printer/node_modules/thermalprinter/node_modules/sleep) while trying to load thermalprinter
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.10-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "thermalprinter" "--save"
gyp ERR! cwd /home/pi/core/printer/node_modules/thermalprinter/node_modules/sleep
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
[sleep]: Error: Failed to execute 'node-gyp rebuild thermalprinter --save' (1)
-
> deasync@0.0.10 install /home/pi/core/printer/node_modules/thermalprinter/node_modules/deasync
> node ./build.js

Installed in `/home/pi/core/printer/node_modules/thermalprinter/node_modules/deasync/bin/linux-arm-node-0.12/deasync.node`
-
> serialport@1.7.4 install /home/pi/core/printer/node_modules/thermalprinter/node_modules/serialport
> node-pre-gyp install --fallback-to-build

make: Entering directory '/home/pi/core/printer/node_modules/thermalprinter/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/obj.target/serialport.node
  COPY Release/serialport.node
  COPY /home/pi/core/printer/node_modules/thermalprinter/node_modules/serialport/build/serialport/v1.7.4/Release/node-v14-linux-arm/serialport.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/pi/core/printer/node_modules/thermalprinter/node_modules/serialport/build'
npm ERR! Linux 4.1.10-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "thermalprinter" "--save"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! sleep@1.2.0 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@1.2.0 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/core/printer/npm-debug.log

````

**Comment by zettam** [comment]
I've tried updating my node, tried reinstalling it from scratch. Looks like I'm clueless about the issue. :(

**Comment by zettam** [comment]
Maybe this is because of the "sleep" package you got rid of in your commit history.. However I can't find that version on npm.

**Comment by zettam** [comment]
managed to download the master and run npm install on it. works.

**Comment by xseignard** [comment]
Mmm, that's weird. I never had problems like this.

I'll try to update the sleep package to its latest version to see if it fixes your problem.

I'll let you know.

**Comment by xseignard** [comment]
So I updated the lib to version `0.3.0`

Could you tell me if you can install it with `npm install thermalprinter` ?

Regards

**Comment by xseignard** [comment]
Did you try to install the new version?

**Comment by xseignard** [comment]
Hello @zettam any updates?
I close the issue for now, but feel free to reopen if you still have troubles with the version `0.3.0` of this lib.
